version: "3.8"
services:

    php-apache:
        build: './docker/php-apache/'
        container_name: app-php-apache
        depends_on:
            - mysql
        ports:
            - "1410:80"
        volumes:
            - ./:/var/www/
        networks:
            - app-network

    mysql:
        build: './docker/mysql/'
        container_name: app-mysql
        volumes:
            - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
        ports:
            - "1420:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        env_file:
            - ./.env
        networks:
            - app-network

networks:
  app-network:
